version: '2'

services:

#  nginx:
#    image: nginx:1.19.9
#    ports:
#      - "80:80"
#    volumes:
#      - "./etc/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
#      - "./static:/usr/share/nginx/html/static"
#      - "./.logs:/logs"
#    depends_on:
#      - app

  db:
    image: mysql:5.7.33
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: socnet
      MYSQL_USER: socnet
      MYSQL_PASSWORD: socnetpass
    ports:
      # to connect from localhost
      - 127.0.0.1:3306:3306
    volumes:
      - ./.data:/var/lib/mysql
      - ./docker/db/master.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      # - ./.logs/mysql:/var/log/mysql
    mem_limit: 6000M

  cache:
    image: memcached:1.6.9-alpine

  db_slave_1:
    image: mysql:5.7.33
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: socnet
      MYSQL_USER: socnet
      MYSQL_PASSWORD: socnetpass
    ports:
      # to connect from localhost
      - 127.0.0.1:3307:3306
    volumes:
      - ./.data_db_slave_1:/var/lib/mysql
      - ./docker/db/slave_1.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      # - ./.logs/mysql:/var/log/mysql
    depends_on:
      - db
    mem_limit: 6000M

  db_slave_2:
    image: mysql:5.7.33
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: socnet
      MYSQL_USER: socnet
      MYSQL_PASSWORD: socnetpass
    ports:
      # to connect from localhost
      - 127.0.0.1:3308:3306
    volumes:
      - ./.data_db_slave_2:/var/lib/mysql
      - ./docker/db/slave_2.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      # - ./.logs/mysql:/var/log/mysql
    depends_on:
      - db
    mem_limit: 6000M

  db_balancer:
    image: haproxy:2.4.0-alpine
    volumes:
      - ./docker/haproxy_mysql.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 127.0.0.1:8082:8080
      - 3306
      - 3307
    depends_on:
      - db
      - db_slave_1
      - db_slave_2

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
#    depends_on:
#      - db
#      - db_slave_1

  app:
    tty: true
    mem_limit: 1500M
    build:
      context: ./
      dockerfile: Dockerfile
    image: &app app
    environment:
      WAIT_HOSTS: db:3306, db_balancer:3306, db_balancer:3307
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30

#      DATABASE_URL: mysql://socnet:socnetpass@db:3306/socnet
#      DATABASE_RO_URL: mysql://socnet_ro:socnetpass@db_slave_1:3306/socnet
      DATABASE_URL: mysql://socnet:socnetpass@db_balancer:3306/socnet
      DATABASE_RO_URL: mysql://socnet_ro:socnetpass@db_balancer:3307/socnet
    ports:
      - 127.0.0.1:8080:8080
    command: ash -c "/wait && python server.py"
    volumes:
      - ./:/app
    depends_on:
      - db_balancer
      - cache
      - rabbit

  worker:
    image: *app
    command: ash -c "/wait && python worker.py"
    environment:
      WAIT_HOSTS: db:3306, db_balancer:3306, db_balancer:3307
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30

      DATABASE_URL: mysql://socnet:socnetpass@db_balancer:3306/socnet
      DATABASE_RO_URL: mysql://socnet_ro:socnetpass@db_balancer:3307/socnet

    volumes:
      - ./:/app
    depends_on:
      - db_balancer
      - cache
      - rabbit

  rabbit:
    image: rabbitmq:3-management-alpine
    hostname: rabbit
    ports:
      - 5672:5672
      - 127.0.0.1:15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: vhost
    volumes:
      - ./.data_rabbit:/var/lib/rabbitmq

  wrk:
    image: williamyeh/wrk:latest
#    depends_on:
#      - app

