version: '2'

services:

#  nginx:
#    image: nginx:1.19.9
#    ports:
#      - "80:80"
#    volumes:
#      - "./etc/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
#      - "./static:/usr/share/nginx/html/static"
#      - "./.logs:/logs"
#    depends_on:
#      - app

  db:
    image: mysql:5.7.33
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: socnet
      MYSQL_USER: socnet
      MYSQL_PASSWORD: socnetpass
    ports:
      # to connect from localhost
      - 127.0.0.1:3306:3306
    volumes:
      - ./.data:/var/lib/mysql
      - ./.logs/mysql:/var/log/mysql
    mem_limit: 6000M

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

  app:
    tty: true
    mem_limit: 1500M
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30

      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: socnet
      DATABASE_PASSWORD: socnetpass
      DATABASE_DB: socnet

    ports:
      - 127.0.0.1:8080:8080
#    command: /wait ; cd /app/ && python server.py
    command: ash -c "/wait && python server.py"
    volumes:
      - ./:/app
    depends_on:
      - db

  wrk:
    image: williamyeh/wrk:latest
    depends_on:
      - app

