version: '2'

services:

#  nginx:
#    image: nginx:1.19.9
#    ports:
#      - "80:80"
#    volumes:
#      - "./etc/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
#      - "./static:/usr/share/nginx/html/static"
#      - "./.logs:/logs"
#    depends_on:
#      - app

  db:
    image: mysql:5.7.33
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: socnet
      MYSQL_USER: socnet
      MYSQL_PASSWORD: socnetpass
      LANG: C.UTF-8

    ports:
      # to connect from localhost
      - 127.0.0.1:3306:3306
    volumes:
      - ./.data_db:/var/lib/mysql
      - ./docker/db/master.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      # - ./.logs/mysql:/var/log/mysql
    mem_limit: 6000M

  redis:
    image: redis:6.2.3-alpine
    volumes:
      - ./.data_redis:/data

  rabbitmq:
#    image: heidiks/rabbitmq-delayed-message-exchange:3.8.9-management
    image: rabbitmq:3.8.19-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
#      - 4369:4369
#      - 5671:5671
#      - 15691:15691
#      - 15692:15692
#      - 25672:25672

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  app:
    tty: true
    mem_limit: 1500M
    build:
      context: ./
      dockerfile: Dockerfile
    image: &app socnet-app
    environment:
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
      FERNET_KEY: 'sIv6jBFwPkNSZP4gVUmzQUnsaMs7g1g7UMRStf5RpCM='

      DATABASE_URL: mysql://socnet:socnetpass@db:3306/socnet
#      DATABASE_RO_URL: mysql://socnet_ro:socnetpass@db_slave_1:3306/socnet
#      DATABASE_URL: mysql://socnet:socnetpass@db_balancer:3306/socnet
#      DATABASE_RO_URL: mysql://socnet_ro:socnetpass@db_balancer:3307/socnet

#      TARANTOOL_URL: tarantool://tarantool:3301

      REDIS_URL: redis://redis:6379
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - 127.0.0.1:8080:8080
    command: ash -c "/wait && python server.py"
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
      - rabbitmq

  worker:
    image: *app
    command: ash -c "/wait && arq worker.WorkerSettings"
    environment:
#      WAIT_HOSTS: db:3306, db_balancer:3306, db_balancer:3307
      WAIT_HOSTS: db:3306, rabbitmq:5672
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30

      DATABASE_URL: mysql://socnet:socnetpass@db:3306/socnet

#      DATABASE_URL: mysql://socnet:socnetpass@db_balancer:3306/socnet
#      DATABASE_RO_URL: mysql://socnet_ro:socnetpass@db_balancer:3307/socnet

      REDIS_URL: redis://redis:6379
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis


  wrk:
    image: williamyeh/wrk:latest
    depends_on:
      - app


  nb:
    image: app-nb
    ports:
      - 127.0.0.1:8899:8899
    build:
      context: ./
      dockerfile: ./docker/ipython.Dockerfile
    command: ipython notebook --ip=0.0.0.0 --port=8899 --notebook-dir=./.data_nb/
    volumes:
      - ./.data_nb:/app/.data_nb:rw
