{
 "title": "socnet",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(servers.apphost.*.*.*.social_net.*.*.*.*.*.*.total.*.*.docker_container_blkio.io_service_bytes_recursive_total), 6, 16)"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.apphost.*.*.*.social_net.*.*.*.*.*.*.*.*.docker_container_mem.usage, 5, 6)"
    },
    {
     "target": "aliasByNode(servers.apphost.*.*.*.social_net.app.*.social_net_app.social_net_app_1.*.*.*.*.*.docker_container_mem.usage, 5, 6)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.apphost.*.*.*.social_net.*.*.mysql.*.running.*.cpu-total.*.*.docker_container_cpu.usage_percent, 9, 12)"
    },
    {
     "target": "aliasByNode(servers.apphost.*.*.*.social_net.app.*.social_net_app.social_net_app_1.*.*.*.*.*.*.docker_container_cpu.usage_percent, 5, 6)"
    }
   ]
  },
  {
   "title": "NET",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(servers.apphost.*.*.*.social_net.*.*.*.*.*.*.*.total.*.docker_container_net.tx_bytes), 5, 6, 16)"
    },
    {
     "target": "aliasByNode(derivative(servers.apphost.*.*.*.social_net.*.*.*.*.*.*.*.total.*.docker_container_net.rx_bytes), 5, 6, 16)"
    }
   ]
  }
 ]
}